### ISSUE TITLE
.NETStandard support

### ISSUE THREAD

**Issue by pellet** [cake-contrib/Cake.AndroidAppManifest#14]
Any plans to support .NETStandard? I managed to find a fork on here which added support.

**Comment by jzeferino** [comment]
@pellet we were working on it at #12.

**Comment by pellet** [comment]
👍

**Comment by jzeferino** [comment]
@pellet 

Added .NET Standard support, please give it a ride and let me know.

https://www.nuget.org/packages/Cake.AndroidAppManifest/1.0.3

thank you @gentledepp

**Comment by pellet** [comment]
Thanks @jzeferino I ended up just using the standard c# xml parser to do the work.  I ran into an issue of reading/writing to the same android manifest file.  It seemed like the stream might not have finished reading before writing it out which was causing the manifest file to not write out the end tag properly.  This might just be happening on mac os though?

**Comment by jzeferino** [comment]
@pellet that problem that you pointed out maybe due to #16. And its already solved.
Could you give it a try?
