### ISSUE TITLE
Write Doesn't Wipe Old File

### ISSUE THREAD

**Issue by lprichar** [cake-contrib/Cake.AndroidAppManifest#16]
If you call `SerializeAppManifest` and the size of the new manifest is smaller than the size of the manifest on disk, then you get an invalid manifest.  The problem is that the file isn't getting wiped before it's written.  The problem is described here: https://stackoverflow.com/questions/3653132/file-openwrite-appends-instead-of-wiping-contents.  I'll submit a PR to fix shortly.

**Comment by jzeferino** [comment]
Thank for the PR, will review it soon.

**Comment by jzeferino** [comment]
Closed by #17.
