### ISSUE TITLE
Support for Cake 0.18.0

### ISSUE THREAD

**Issue by markmadlangbayan** [cake-contrib/Cake.AndroidAppManifest#2]
This has been working, until I'm getting the following:

`The assembly 'Cake.AndroidAppManifest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.13.0). This assembly need to reference at least Cake.Core version 0.16.0. Another option is to downgrade Cake to an earlier version.`

**Comment by ghuntley** [comment]
Can you please send in a pull-request to upgrade the library to the latest version of Cake? (i.e. right click -> upgrade packages)

**Comment by lzettl** [comment]
PR https://github.com/ghuntley/Cake.AndroidAppManifest/pull/4 should resolve the above issue.

**Comment by jzeferino** [comment]
@ghuntley how are we on this? Can I PR to support cake 0.19.5?

**Comment by devlead** [comment]
#4 should sort 0.19.5 too, is it pushed to nuget?

**Comment by jzeferino** [comment]
The current nuget version of Cake.AndroidAppManifest is targeting a version below 0.18.0.

> The assembly 'Cake.AndroidAppManifest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.13.0). This assembly need to reference at least Cake.Core version 0.16.0. Another option is to downgrade Cake to an earlier version.

**Comment by jzeferino** [comment]
@ghuntley I've created a [PR](https://github.com/cake-contrib/Cake.AndroidAppManifest/pull/7) with it. When you have time, please review it and update the nuget.
