### ISSUE TITLE
'AndoridAppManifestAliases' typo not corrected in class name

### ISSUE THREAD

**Issue by jnm2** [cake-contrib/Cake.AndroidAppManifest#24]
The filename was fixed in https://github.com/cake-contrib/Cake.AndroidAppManifest/commit/14606b0, but not the class name:

https://github.com/cake-contrib/Cake.AndroidAppManifest/blob/ec01f891a4ff0ec288338a4f4db972b5f6d09598/src/Cake.AndroidAppManifest/AndroidAppManifestAliases.cs#L12

It also shows up on the Cake website misspelled: https://www.cakebuild.net/api/Cake.AndroidAppManifest/AndoridAppManifestAliases/

**Comment by jzeferino** [comment]
Will fix this ASAP.

**Comment by jzeferino** [comment]
Fixed in #25.
Released it already https://www.nuget.org/packages/Cake.AndroidAppManifest/1.0.4

@gep13 how can I update the cake docs?

**Comment by gep13** [comment]
> @jzeferino said...
 how can I update the cake docs?

They will be updated the next time the site is built.  We have a hotfix coming out soon, so it shouldn't be too long before it appears.

**Comment by jzeferino** [comment]
Fixed.
