### ISSUE TITLE
Update to latest cake

### ISSUE THREAD

**Issue by Cheesebaron** [cake-contrib/Cake.AndroidAppManifest#29]
We have to run with skip verification. It is not nice. Please update.

**Comment by jzeferino** [comment]
@Cheesebaron let me see if the update breaks anything and I will update it.

**Comment by Cheesebaron** [comment]
I have something ready for a PR. Will wrap it up and create it.

**Comment by jzeferino** [comment]
Take a look at https://www.nuget.org/packages/Cake.AndroidAppManifest/1.1.0 and give me feedback @Cheesebaron
