### ISSUE TITLE
Update cake version and new nuget release.

### ISSUE THREAD

**Issue by jzeferino** [cake-contrib/Cake.AndroidAppManifest#9]
I can PR again with the most recent Cake version. Are you interested?
Can you release the new nuget with the last changes #7?

**Comment by aloisdeniel** [comment]
Yep need this merge too, because at the moment we can't use it with `Cake.MobileCenter` which is frustrating!

**Comment by jzeferino** [comment]
@ghuntley please take a look. :shamrock:

**Comment by ghuntley** [comment]
@jzeferino do you want to take over and help out with maintenance of this add-in?

**Comment by jzeferino** [comment]
@ghuntley yes, I can help with that.

**Comment by ghuntley** [comment]
Excellent. 

@gep13 can you please promote @jzeferino to maintainer status. Also I'd be keen in seeing all my build infrastructure 🔥 to the ground and changed to generic cake-contrib infrastructure.

**Comment by jzeferino** [comment]
@ghuntley what do you mean by generic cake-contrib infrastructure? `Cake.Recipe`?

**Comment by gep13** [comment]
@ghuntley as requested, I have added @jzeferino with permissions to this repository.  GitHub to AppVeyor permissions are currently synchronising...

**Comment by jzeferino** [comment]
@ghuntley @gep13 I will need nuget permissions too, to release new versions of the Addin.

**Comment by gep13** [comment]
@jzeferino we can certainly arrange that, however, if we go down to the route of using Cake.Recipe, which is what I think @ghuntley was suggesting, the new packages will be pushed using the cake-contrib user to nuget.org.

Either way, let me now your username on NuGet.org, and I can get you added as a co-owner of the package over there.

**Comment by jzeferino** [comment]
@gep13 my nuget username is jzeferino.

**Comment by gep13** [comment]
@jzeferino I have added you as a co-owner.  As mentioned, ideally the cake-contrib user would be used to do the push though.

**Comment by aloisdeniel** [comment]
Any news? **Cake.PList** has been updated, this package is the last blocking step for having a fully supported **Mobile Center** cake script!

**Comment by jzeferino** [comment]
@aloisdeniel we are [working](https://github.com/cake-contrib/Cake.AndroidAppManifest/pull/12) on it.

**Comment by jzeferino** [comment]
I've updated Cake.Manifest to .Net framework 4.6.2 and cake to 0.22.2. Please give it a [try](https://www.nuget.org/packages/Cake.AndroidAppManifest/1.0.2) @aloisdeniel

**Comment by ghuntley** [comment]
Thanks @jzeferino

**Comment by aloisdeniel** [comment]
Yep, I can confirm : it works great for me! Thanks @jzeferino !

**Comment by gep13** [comment]
Great work @jzeferino!
